module.exports = {
  GACHA_COST_NORMAL: 100,
  GACHA_COST_PREMIUM: 500,
  DAILY_COINS: 500,
  SHINY_RATE: 0.05,
  COMBAT_MIN_REWARD: 50,
  COMBAT_MAX_REWARD: 150,
  COMBAT_XP_BASE: 30,
  MAX_LEVEL: 100,
  POKEMON_PER_PAGE: 20,
  MAX_TEAM_SIZE: 6,
  JWT_EXPIRES_IN: '7d'
};
